title: eromatsuri's Tech Blog
description: 技術メモと日記のブログ
url: "https://eromatsuri-ero.github.io"
baseurl: ""

theme: minimal-mistakes-jekyll

# GitHub Pagesで使える公式プラグインのみ
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Minimal Mistakes 基本設定
minimal_mistakes_skin: "default"  # dark に変えてもOK
locale: "ja"

# 投稿設定
permalink: /:categories/:title/

# タグページを有効化するための設定
collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
