title: タイトル考え中
description: 技術メモと日記のブログ
url: "https://eromatsuri-ero.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

locale: ja
minimal_mistakes_skin: default

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "eromatsuri"
  bio: "有機栽培エンジニア"
  location: "Japan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/eromatsuri-ero"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

tag_archive:
  type: liquid
  path: /tags/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: false

footer:
  links: []
