title: eromatsuri's Tech Blog
description: 技術メモと日記のブログ
url: "https://eromatsuri-ero.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

locale: "ja"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

permalink: /:categories/:title/

author:
  name: "eromatsuri"
  bio: "有機栽培エンジニア"
  location: "Japan"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/eromatsuri-ero"

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: false

include:
  - _includes

footer:
  links: []